name: Build and deploy

on:
  push:
    branches: ["main"]
    tags: ["v*"]

jobs:
  build:
    runs-on: ubuntu-24.04
    environment: prod
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - name: Install AWS CLI
        uses: unfor19/install-aws-cli-action@v1
        with:
          version: 1
          arch: amd64

      - name: Build static pages
        run: npm ci --omit=dev && npm run build

      - name: Upload to S3
        run: aws s3 sync dist s3://valnetten
        env:
          # AWS_DEFAULT_REGION: garage
          # AWS_ENDPOINT_URL: https://s3.juliamertz.dev 
          AWS_DEFAULT_REGION: auto
          AWS_ENDPOINT_URL: https://2b3473f287c2ddf45a7105b22e69c7a9.r2.cloudflarestorage.com
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
